<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Approve probe</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="approve_files/libs/clipboard/clipboard.min.js"></script>
<script src="approve_files/libs/quarto-html/quarto.js"></script>
<script src="approve_files/libs/quarto-html/popper.min.js"></script>
<script src="approve_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="approve_files/libs/quarto-html/anchor.min.js"></script>
<link href="approve_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="approve_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="approve_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="approve_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="approve_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Approve probe</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="cell-output-display">
<div id="fig-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="approve_files/figure-html/fig-1-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Percentage of <code>yes</code> responses to declarative and sarcastic items</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-1">Figure&nbsp;1</a> shows the overall percentage of “yes” responses for both groups combined in the two intonation types. As seen in the figure, “yes” was more frequent in declarative items overall (41.5%) than in sarcastic items (33.9%). The figure represents a total of 1195 trials for the declarative and 1200 for the sarcastic condition.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="approve_files/figure-html/fig-2-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Percentage of <code>yes</code> responses to declarative and sarcastic items in both groups</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-2">Figure&nbsp;2</a> shows the overall percentage of “yes” responses for both groups individually in the two intonation types. “Yes” was the most frequent in declarative items for children (53.5%), followed by sarcastic items in children (43.7%). The adults had a lower percentage in both cases, but also had a higher percentage in declarative intonation(36.3%) than sarcastic (29.6%). Notably, there was more data overall in the adult data set than children: there were 1668 total data points for adults and 727 data points for children.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="approve_files/figure-html/fig-3-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Percentage of <code>yes</code> responses by modifier type overall</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-3">Figure&nbsp;3</a> shows the overall percentage of “yes” responses for the of the three modifier types overall. “Yes” was the most frequent in grad+subj+pos items (72.4%), followed by -grad–subj items (28.1%), and finally grad+subj+neg with 12.5%).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="approve_files/figure-html/fig-4-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Percentage of <code>yes</code> responses by modifier type in both groups</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-4">Figure&nbsp;4</a> breaks down the percentage of “yes” responses for the of the three modifier types by groups. The highest percentage was in children for grad+subj+pos (80.5%), followed by adults in the same condition (68.9%). In the –grad–subj modifier type, children again has a higher percentage of yes responses (44.7%) relative to adults (21%) The same trend was observed for the final modifier type of grad+subj+neg (children: 20.3%; adults 9%).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="approve_files/figure-html/fig-5-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Percentage of <code>yes</code> responses in each modifier type and intonation</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-5">Figure&nbsp;5</a> breaks down the percentage of “yes” responses for the of the three modifier types by intonation insead of groups. The highest percentage was for declaratives for grad+subj+pos (81.5%), followed by sarcastic items in the same condition (63.4%). In the –grad–subj modifier type, declarative utterances were shown to have a higher percentage of yes responses (31.8%) relative to sarcastic ones (24.4%) The opposite trend was observed for the final modifier type of grad+subj+neg, though the difference was small (delcarative: 11.2%; sarcastic 13.8%).</p>
<section id="model-results" class="level3">
<h3 class="anchored" data-anchor-id="model-results">Model Results</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="approve_files/figure-html/fig-6-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Percentage of <code>yes</code> responses by modifier type and intonation in both groups</figcaption>
</figure>
</div>
</div>
</div>
<p>Finally, <a href="#fig-6">Figure&nbsp;6</a> breaks down the percentage of “yes” responses for the of the three modifier types by both intonation and between groups. Many of differences were tested directly in the Bayesian Logistic regression models. The logistic regression model are summarized in the tables below and test the differences the log-odds of answering “yes” for both sarcastic and declarative intonation in both groups. An individual model was run each of the three modifier types.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Table 1: Description of the posterior distribution for the Bayesian Logistic regression for -grad-subj. </caption>
<colgroup>
<col style="width: 24%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">MAP</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">pd</th>
<th style="text-align: right;">ps</th>
<th style="text-align: right;">ROPE_CI</th>
<th style="text-align: right;">ROPE_low</th>
<th style="text-align: right;">ROPE_high</th>
<th style="text-align: right;">ROPE_Percentage</th>
<th style="text-align: right;">Rhat</th>
<th style="text-align: right;">ESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">b_Intercept</td>
<td style="text-align: right;">-1.832</td>
<td style="text-align: right;">-1.842</td>
<td style="text-align: right;">-1.835</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-2.450</td>
<td style="text-align: right;">-1.298</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">3065.378</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic</td>
<td style="text-align: right;">-0.428</td>
<td style="text-align: right;">-0.432</td>
<td style="text-align: right;">-0.361</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.958</td>
<td style="text-align: right;">0.073</td>
<td style="text-align: right;">0.953</td>
<td style="text-align: right;">0.833</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.149</td>
<td style="text-align: right;">0.999</td>
<td style="text-align: right;">5741.468</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b_groupchildren</td>
<td style="text-align: right;">2.009</td>
<td style="text-align: right;">2.019</td>
<td style="text-align: right;">2.067</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.239</td>
<td style="text-align: right;">2.897</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.001</td>
<td style="text-align: right;">2762.072</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic:groupchildren</td>
<td style="text-align: right;">-0.434</td>
<td style="text-align: right;">-0.429</td>
<td style="text-align: right;">-0.454</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-1.210</td>
<td style="text-align: right;">0.380</td>
<td style="text-align: right;">0.849</td>
<td style="text-align: right;">0.722</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.219</td>
<td style="text-align: right;">0.999</td>
<td style="text-align: right;">4935.168</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 1 shows the model for the modifier type <code>-grad-subj</code> and is visualized in the left panel of <a href="#fig-6">Figure&nbsp;6</a>. The intercept term predicts the log-odds of choosing “yes” for declarative items by adults -1.832 [95% HDI -2.45 - -1.298]. This corresponds to a median probability of 0.14 (ranging from 0.08 to 0.21). The fixed effect “intonationsarcastic” tests whether there was a difference in the adult group between declarative and sarcastic intonation. The model suggests that the effect is negative (-0.428), and possibly exists (pd = 0.953). This can be taken as moderate evidence that adults were less likely to respond “yes” to trials with sarcastic intonation than declarative intonation in the <code>-grad-subj</code> modifier condition, although the effect is small (predicted probability of .13 and .1 respectively. There was compelling evidence that the children were more likely to answer “yes” than adults in the declarative condition 2.009 [95% HDI 1.239 - 2.897; pd = 1]. Finally, there was not compelling evidence of an interaction -0.434 [95% HDI -1.21 - 0.38; pd = 0.849], suggesting that there was not reliable evidence that children were more likely to respond “yes” as a function of intonation for the <code>-grad-subj</code> modifier condition. However, there was also not sufficient evidence for practical equivalence, suggesting that this result is inconclusive, rather than null [ROPE bounds = +/- .18; ROPE percentage: 0.219].</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Table 2: Description of the posterior distribution for the Bayesian Logistic regression for grad+subj+neg. </caption>
<colgroup>
<col style="width: 24%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">MAP</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">pd</th>
<th style="text-align: right;">ps</th>
<th style="text-align: right;">ROPE_CI</th>
<th style="text-align: right;">ROPE_low</th>
<th style="text-align: right;">ROPE_high</th>
<th style="text-align: right;">ROPE_Percentage</th>
<th style="text-align: right;">Rhat</th>
<th style="text-align: right;">ESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">b_Intercept</td>
<td style="text-align: right;">-4.282</td>
<td style="text-align: right;">-4.324</td>
<td style="text-align: right;">-4.171</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-5.774</td>
<td style="text-align: right;">-3.102</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.002</td>
<td style="text-align: right;">1306.805</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic</td>
<td style="text-align: right;">1.110</td>
<td style="text-align: right;">1.121</td>
<td style="text-align: right;">1.056</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.331</td>
<td style="text-align: right;">1.995</td>
<td style="text-align: right;">0.998</td>
<td style="text-align: right;">0.990</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.999</td>
<td style="text-align: right;">2407.624</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b_groupchildren</td>
<td style="text-align: right;">2.348</td>
<td style="text-align: right;">2.368</td>
<td style="text-align: right;">2.268</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.302</td>
<td style="text-align: right;">3.545</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1939.217</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic:groupchildren</td>
<td style="text-align: right;">-1.588</td>
<td style="text-align: right;">-1.594</td>
<td style="text-align: right;">-1.566</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-2.785</td>
<td style="text-align: right;">-0.472</td>
<td style="text-align: right;">0.998</td>
<td style="text-align: right;">0.994</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">2505.010</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 2 shows the model for the modifier type <code>grad+subj+neg</code> and is visualized in the middle panel of <a href="#fig-6">Figure&nbsp;6</a>. Again, the intercept term predicts the log-odds of choosing “yes” for declarative items by adults -4.282 [95% HDI -5.774 - -3.102]. This corresponds to a very small median probability of 0.01 (ranging from 0 to 0.04).</p>
<p>There was compelling evidence for an increase in “yes” responses in adults for sarcastic items relative to declarative ones [Median = 1.11; 95% HDI <code>repmod2$CI_low[2] - repmod2$CI_high[2]</code>, and certainly exists (pd = 0.998). However, this effect is a rather small increase in which the model predicts the median probability to be just 0.04.</p>
<p>Like the first model, there was again compelling evidence that the children were more likely to answer “yes” than adults in the declarative condition 2.348 [95% HDI 1.302 - 3.545; pd = 1]. Unlike the first model, there was compelling evidence of an interaction -1.588 [95% HDI -2.785 - -0.472; pd = 0.998], suggesting that there children were overall less likely to respond “yes” when the intonation was sarcastic.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Table 3: Description of the posterior distribution for the Bayesian Logistic regression for grad+subj+pos </caption>
<colgroup>
<col style="width: 24%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">MAP</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">pd</th>
<th style="text-align: right;">ps</th>
<th style="text-align: right;">ROPE_CI</th>
<th style="text-align: right;">ROPE_low</th>
<th style="text-align: right;">ROPE_high</th>
<th style="text-align: right;">ROPE_Percentage</th>
<th style="text-align: right;">Rhat</th>
<th style="text-align: right;">ESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">b_Intercept</td>
<td style="text-align: right;">1.893</td>
<td style="text-align: right;">1.895</td>
<td style="text-align: right;">1.876</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.976</td>
<td style="text-align: right;">2.864</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.999</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.002</td>
<td style="text-align: right;">2160.278</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic</td>
<td style="text-align: right;">-1.485</td>
<td style="text-align: right;">-1.488</td>
<td style="text-align: right;">-1.484</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-1.980</td>
<td style="text-align: right;">-1.001</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">4369.449</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b_groupchildren</td>
<td style="text-align: right;">0.712</td>
<td style="text-align: right;">0.719</td>
<td style="text-align: right;">0.687</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.109</td>
<td style="text-align: right;">1.573</td>
<td style="text-align: right;">0.957</td>
<td style="text-align: right;">0.900</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.079</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">3973.778</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic:groupchildren</td>
<td style="text-align: right;">0.467</td>
<td style="text-align: right;">0.467</td>
<td style="text-align: right;">0.483</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.460</td>
<td style="text-align: right;">1.392</td>
<td style="text-align: right;">0.842</td>
<td style="text-align: right;">0.724</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.202</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">4303.740</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Finally, Table 3 shows the model for the modifier type <code>grad+subj+pos</code> and is visualized in the right panel of <a href="#fig-6">Figure&nbsp;6</a>. The log-odds of choosing “yes” for declarative items by adults was much higher than the other two modifier types 1.893 [95% HDI 0.976 - 2.864]. This corresponds to a median probability of 0.87 (ranging from 0.73 to 0.95). Again, there was an effect of intonation in adults, in which there was compelling evidence for an decrease in “yes” responses in adults for sarcastic items relative to declarative ones [Median = -1.485; 95% HDI <code>repmod3$CI_low[2] - repmod3$CI_high[2]</code>; pd = 1]. There was also a possible effect of group for declarative intonation, in which there was compelling evidence for an increase in “yes” responses for children relative to adults [Median = -1.485; 95% HDI <code>repmod3$CI_low[2] - repmod3$CI_high[2]</code>; pd = 1]. Finally, there was not compelling evidence of an interaction 0.467 [95% HDI -0.46 - 1.392; pd = 0.842], suggesting that there was not reliable evidence that children were more likely to respond “yes” as a function of intonation. However, there was also not sufficient evidence for practical equivalence, suggesting that this result is inconclusive, rather than null [ROPE bounds = +/- .18; ROPE percentage: 0.202].</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>