<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mean probe</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="mean_files/libs/clipboard/clipboard.min.js"></script>
<script src="mean_files/libs/quarto-html/quarto.js"></script>
<script src="mean_files/libs/quarto-html/popper.min.js"></script>
<script src="mean_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="mean_files/libs/quarto-html/anchor.min.js"></script>
<link href="mean_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mean_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="mean_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="mean_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="mean_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mean probe</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  intonation      n
  &lt;chr&gt;       &lt;int&gt;
1 declarative  1204
2 sarcastic    1203</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mean_files/figure-html/fig-1-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Percentage of <code>yes</code> responses to declarative and sarcastic items</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-1">Figure&nbsp;1</a> shows the overall percentage of “yes” responses for both groups combined in the two intonation types. As seen in the figure, “yes” was more frequent in declarative items overall (86.2%) than in sarcastic items (77.2%). The figure represents a total of 1204 trials for the declarative and 1203 for the sarcastic condition.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mean_files/figure-html/fig-2-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Percentage of <code>yes</code> responses to declarative and sarcastic items in both groups</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-2">Figure&nbsp;2</a> shows the overall percentage of “yes” responses for both groups individually in the two intonation types. In this case, “yes” was the most frequent in declarative items for adults (88.4%), followed by declarative items in children (81.4%).</p>
<p>The sarcastic items had a lower percentage in both groups, (adults: 77.2%, children; 77.2%). Again, there was more data overall in the adult data set than children: there were 1668 total data points for adults and 739 data points for children.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mean_files/figure-html/fig-3-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Percentage of <code>yes</code> responses by modifier type overall</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-3">Figure&nbsp;3</a> shows the overall percentage of “yes” responses for the of the three modifier types overall. “Yes” was the most above 75% in all cases (grad+subj+pos items:77.8%; -grad–subj items (83.2%; grad+subj+neg 84.2%).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mean_files/figure-html/fig-4-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Percentage of <code>yes</code> responses by modifier type in both groups</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-4">Figure&nbsp;4</a> breaks down the percentage of “yes” responses for the of the three modifier types by groups. Overall, the percentages of “yes” responses ranged from 74.6% to 88.7%</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mean_files/figure-html/fig-5-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Percentage of <code>yes</code> responses in each modifier type and intonation</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-5">Figure&nbsp;5</a> breaks down the percentage of “yes” responses for the of the three modifier types by intonation instead of groups. Here, the lowest percentage of “yes” responses was 70.2 and the highest was 89.6.</p>
<section id="model-results" class="level3">
<h3 class="anchored" data-anchor-id="model-results">Model Results</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mean_files/figure-html/fig-6-1.png" class="img-fluid figure-img" width="4200"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Percentage of <code>yes</code> responses by modifier type and intonation in both groups</figcaption>
</figure>
</div>
</div>
</div>
<p>Finally, <a href="#fig-6">Figure&nbsp;6</a> breaks down the percentage of “yes” responses for the of the three modifier types by both intonation and between groups. Many of these differences were tested directly in the Bayesian Logistic regression models. The logistic regression model are summarized in the tables below and test the differences the log-odds of answering “yes” for both sarcastic and declarative intonation in both groups. An individual model was run each of the three modifier types.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Table 1: Description of the posterior distribution for the Bayesian Logistic regression for -grad-subj. </caption>
<colgroup>
<col style="width: 24%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">MAP</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">pd</th>
<th style="text-align: right;">ps</th>
<th style="text-align: right;">ROPE_CI</th>
<th style="text-align: right;">ROPE_low</th>
<th style="text-align: right;">ROPE_high</th>
<th style="text-align: right;">ROPE_Percentage</th>
<th style="text-align: right;">Rhat</th>
<th style="text-align: right;">ESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">b_Intercept</td>
<td style="text-align: right;">3.075</td>
<td style="text-align: right;">3.094</td>
<td style="text-align: right;">3.065</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">2.393</td>
<td style="text-align: right;">3.937</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.001</td>
<td style="text-align: right;">1802.501</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic</td>
<td style="text-align: right;">-0.219</td>
<td style="text-align: right;">-0.220</td>
<td style="text-align: right;">-0.214</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.814</td>
<td style="text-align: right;">0.360</td>
<td style="text-align: right;">0.761</td>
<td style="text-align: right;">0.551</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.375</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">3792.865</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b_groupchildren</td>
<td style="text-align: right;">-0.919</td>
<td style="text-align: right;">-0.918</td>
<td style="text-align: right;">-1.036</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-1.981</td>
<td style="text-align: right;">0.135</td>
<td style="text-align: right;">0.959</td>
<td style="text-align: right;">0.916</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1880.075</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic:groupchildren</td>
<td style="text-align: right;">0.247</td>
<td style="text-align: right;">0.246</td>
<td style="text-align: right;">0.233</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.716</td>
<td style="text-align: right;">1.231</td>
<td style="text-align: right;">0.694</td>
<td style="text-align: right;">0.550</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.269</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">3424.304</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 1 shows the model for the modifier type <code>-grad-subj</code> and is visualized in the left panel of <a href="#fig-6">Figure&nbsp;6</a>. The intercept term predicts the log-odds of choosing “yes” for declarative items by adults 3.075 [95% HDI 2.393 - 3.937]. This corresponds to a median probability of 0.96 (ranging from 0.92 to 0.98). The fixed effect “intonationsarcastic” tests whether there was a difference in the adult group between declarative and sarcastic intonation. The model results were inconclusive for this comparison [-0.219; 95% HDI -0.814 - 0.36; pd = 0.761]. There was also not sufficient evidence to consider the two conditions practically equivalent [ ]. The model suggests that there is possible evidence that the children were less likely to answer “yes” than adults in the declarative condition -0.919 [95% HDI -1.981 - 0.135; pd = 0.959]. Finally, there was not compelling evidence of an interaction 0.247 [95% HDI -0.716 - 1.231; pd = 0.694], suggesting that there was not reliable evidence that children were more likely to respond “yes” as a function of intonation for the <code>-grad-subj</code> modifier condition. Again, there was also not sufficient evidence for practical equivalence, suggesting that this result is inconclusive, rather than null [ROPE percentage: 0.269].</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Table 2: Description of the posterior distribution for the Bayesian Logistic regression for grad+subj+neg. </caption>
<colgroup>
<col style="width: 24%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">MAP</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">pd</th>
<th style="text-align: right;">ps</th>
<th style="text-align: right;">ROPE_CI</th>
<th style="text-align: right;">ROPE_low</th>
<th style="text-align: right;">ROPE_high</th>
<th style="text-align: right;">ROPE_Percentage</th>
<th style="text-align: right;">Rhat</th>
<th style="text-align: right;">ESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">b_Intercept</td>
<td style="text-align: right;">4.067</td>
<td style="text-align: right;">4.087</td>
<td style="text-align: right;">4.054</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">3.231</td>
<td style="text-align: right;">5.108</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.001</td>
<td style="text-align: right;">1951.109</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic</td>
<td style="text-align: right;">-1.633</td>
<td style="text-align: right;">-1.647</td>
<td style="text-align: right;">-1.623</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-2.402</td>
<td style="text-align: right;">-0.964</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">3088.883</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b_groupchildren</td>
<td style="text-align: right;">-2.003</td>
<td style="text-align: right;">-2.010</td>
<td style="text-align: right;">-2.042</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-3.115</td>
<td style="text-align: right;">-1.003</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.003</td>
<td style="text-align: right;">2255.341</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic:groupchildren</td>
<td style="text-align: right;">0.838</td>
<td style="text-align: right;">0.852</td>
<td style="text-align: right;">0.762</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.156</td>
<td style="text-align: right;">1.874</td>
<td style="text-align: right;">0.953</td>
<td style="text-align: right;">0.905</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">3823.401</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 2 shows the model for the modifier type <code>grad+subj+neg</code> and is visualized in the middle panel of <a href="#fig-6">Figure&nbsp;6</a>. Again, the intercept term predicts the log-odds of choosing “yes” for declarative items by adults 4.067 [95% HDI 3.231 - 5.108]. There was compelling evidence for an increase in “yes” responses in adults for sarcastic items relative to declarative ones [Median = -1.633; 95% HDI <code>repmod2$CI_low[2] - repmod2$CI_high[2]</code>, and certainly exists (pd = 1).</p>
<p>Unlike the first model, there was compelling evidence that the children were less likely to answer “yes” than adults in the declarative condition -2.003 [95% HDI -3.115 - -1.003; pd = 1]. Likewise, there was also possible evidence of an interaction 0.838 [95% HDI -0.156 - 1.874; pd = 0.953], suggesting that there children were overall more likely to respond “yes” when the intonation was sarcastic.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Table 3: Description of the posterior distribution for the Bayesian Logistic regression for grad+subj+pos </caption>
<colgroup>
<col style="width: 24%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">MAP</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">pd</th>
<th style="text-align: right;">ps</th>
<th style="text-align: right;">ROPE_CI</th>
<th style="text-align: right;">ROPE_low</th>
<th style="text-align: right;">ROPE_high</th>
<th style="text-align: right;">ROPE_Percentage</th>
<th style="text-align: right;">Rhat</th>
<th style="text-align: right;">ESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">b_Intercept</td>
<td style="text-align: right;">2.253</td>
<td style="text-align: right;">2.253</td>
<td style="text-align: right;">2.259</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.674</td>
<td style="text-align: right;">2.827</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">3919.434</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic</td>
<td style="text-align: right;">-1.463</td>
<td style="text-align: right;">-1.468</td>
<td style="text-align: right;">-1.451</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-1.957</td>
<td style="text-align: right;">-0.989</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.999</td>
<td style="text-align: right;">5642.576</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b_groupchildren</td>
<td style="text-align: right;">0.325</td>
<td style="text-align: right;">0.336</td>
<td style="text-align: right;">0.306</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.533</td>
<td style="text-align: right;">1.262</td>
<td style="text-align: right;">0.776</td>
<td style="text-align: right;">0.634</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.256</td>
<td style="text-align: right;">0.999</td>
<td style="text-align: right;">4111.162</td>
</tr>
<tr class="even">
<td style="text-align: left;">b_intonationsarcastic:groupchildren</td>
<td style="text-align: right;">1.187</td>
<td style="text-align: right;">1.191</td>
<td style="text-align: right;">1.157</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.205</td>
<td style="text-align: right;">2.153</td>
<td style="text-align: right;">0.992</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.181</td>
<td style="text-align: right;">0.181</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">5701.666</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Finally, Table 3 shows the model for the modifier type <code>grad+subj+pos</code> and is visualized in the right panel of <a href="#fig-6">Figure&nbsp;6</a>. The log-odds of choosing “yes” for declarative items by adults was much higher than the other two modifier types 2.253 [95% HDI 1.674 - 2.827]. This corresponds to a median probability of 0.9 (ranging from 0.84 to 0.94). Again, there was an effect of intonation in adults, in which there was compelling evidence for an decrease in “yes” responses in adults for sarcastic items relative to declarative ones [Median = -1.463; 95% HDI <code>repmod3$CI_low[2] - repmod3$CI_high[2]</code>; pd = 1]. There was also a possible effect of group for declarative intonation, in which there was compelling evidence for an increase in “yes” responses for children relative to adults [Median = -1.463; 95% HDI <code>repmod3$CI_low[2] - repmod3$CI_high[2]</code>; pd = 1]. Finally, there was not compelling evidence of an interaction 1.187 [95% HDI 0.205 - 2.153; pd = 0.992], suggesting that there was not reliable evidence that children were more likely to respond “yes” as a function of intonation. However, there was also not sufficient evidence for practical equivalence, suggesting that this result is inconclusive, rather than null [ROPE bounds = +/- .18; ROPE percentage: 0].</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>